#Ref:https://hierl.dev/posts/rpi-cluster-apps-en/
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pihole-data
  namespace: pihole
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  #volumeName: pihole-data
  resources:
    requests:
      storage: 1Gi
      #replicaCount: 3
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: pihole-pvc-dnsmasq
#   namespace: pihole
# spec:
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: longhorn
#   resources:
#     requests:
#       storage: 500Mi