apiVersion: v1
kind: Service
metadata:
  name: wireguard-svc
  namespace: pihole
  annotations:
    metallb.universe.tf/allow-shared-ip: "pihole"
spec:
  selector:
    app: wireguard
  ports:
    - name: 51820-tcp
      port: 51820
      targetPort: 51820
      protocol: UDP
  externalTrafficPolicy: Local
  type: LoadBalancer
